### ISSUE TITLE
欢迎页闪退

### ISSUE THREAD

**Issue by Luolc** [pku-runner/pku-runner.github.io#4]
trace如下
```
12-13 23:43:27.547 27634-27634/? E/MessageQueue-JNI: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class android.widget.ImageView
                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                         at cn.edu.pku.pkurunner.GuidePage.EntryFragment.onCreateView(EntryFragment.java:19)
                                                         at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                         at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                         at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
                                                         at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
                                                         at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
                                                         at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
                                                         at android.support.v4.view.ViewPager$3.run(ViewPager.java:254)
                                                         at android.support.v4.view.ViewPager.completeScroll(ViewPager.java:1925)
                                                         at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2055)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                         at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                         at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                         at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
                                                         at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                         at android.view.View.dispatchPointerEvent(View.java:9520)
                                                         at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4238)
                                                         at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4104)
                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
                                                         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
                                                         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
                                                         at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3795)
                                                         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
                                                         at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3852)
                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
                                                         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
                                                         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
                                                         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
                                                         at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5932)
                                                         at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5906)
                                                         at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5867)
                                                         at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6035)
                                                         at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                         at android.os.MessageQueue.nativePollOnce(Native Method)
                                                         at android.os.MessageQueue.next(MessageQueue.java:323)
                                                         at android.os.Looper.loop(Looper.java:135)
                                                         at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                      at java.lan
12-13 23:43:28.802 27634-27634/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: cn.edu.pku.pkurunner, PID: 27634
                                                   android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class android.widget.ImageView
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                       at cn.edu.pku.pkurunner.GuidePage.EntryFragment.onCreateView(EntryFragment.java:19)
                                                       at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                       at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
                                                       at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
                                                       at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
                                                       at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
                                                       at android.support.v4.view.ViewPager$3.run(ViewPager.java:254)
                                                       at android.support.v4.view.ViewPager.completeScroll(ViewPager.java:1925)
                                                       at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2055)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                       at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
                                                       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                       at android.view.View.dispatchPointerEvent(View.java:9520)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4238)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4104)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3795)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
                                                       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3852)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
                                                       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5932)
                                                       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5906)
                                                       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5867)
                                                       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6035)
                                                       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                       at android.os.MessageQueue.nativePollOnce(Native Method)
                                                       at android.os.MessageQueue.next(MessageQueue.java:323)
                                                       at android.os.Looper.loop(Looper.java:135)
```

资源文件解析错误，如果开启了instant run，大概率是它导致的

**Comment by owen8877** [comment]
这是0.9.2老版本了，建议下载0.9.3使用。
