### ISSUE TITLE
首页打开drawer后闪退

### ISSUE THREAD

**Issue by Luolc** [pku-runner/pku-runner.github.io#5]
trace如下
```
Process: cn.edu.pku.pkurunner, PID: 27842
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String cn.edu.pku.pkurunner.Model.User.getName()' on a null object reference
                                                       at cn.edu.pku.pkurunner.MainActivity$2.onDrawerOpened(MainActivity.java:238)
                                                       at android.support.v4.widget.DrawerLayout.dispatchOnDrawerOpened(DrawerLayout.java:866)
                                                       at android.support.v4.widget.DrawerLayout.updateDrawerState(DrawerLayout.java:811)
                                                       at android.support.v4.widget.DrawerLayout$ViewDragCallback.onViewDragStateChanged(DrawerLayout.java:2028)
                                                       at android.support.v4.widget.ViewDragHelper.setDragState(ViewDragHelper.java:875)
                                                       at android.support.v4.widget.ViewDragHelper$2.run(ViewDragHelper.java:336)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

空指针，应该挺好复现的

**Comment by owen8877** [comment]
其实我们一直没有重现出来这个bug= =
大概原因估计是drawer的兼容包实现的一些bug什么……我们也不是很清楚（因为重现不了= =）
能提供更具体的设备与pkurunner版本信息么？

**Comment by Luolc** [comment]
应用版本 v0.9.2
设备 Google Nexus 6P Android 6.0.1

建议定位一下`cn.edu.pku.pkurunner.Model.User.getName()`的调用位置，trace里面代码行数也有定位吖`MainActivity.java:238`。大部分bug只分析逻辑就能改啦~ 祝好

**Comment by owen8877** [comment]
虽然我尽量想保持礼貌，但是pkurunner的开发者并不傻= =
要是真像你说的是一个nullPointerException的话，这个bug就不会在release中出现了= =
很早的时候就在bugly上面看到这个crash了，但是身边七八台设备无一能重现bug，所以仅仅简单地判断是否为null并不能解决问题。
另外再次强调一下不要把老版本的bug再提交上来了。
